import { emptyWorkspace,type MemoryItem,type Workspace } from "./restaurant-memory";
export const DEMO_DATE="2026-10-08";
export function demoItems():MemoryItem[]{return [
  {id:"demo-midi",kind:"cash",title:"Relevé de caisse · midi",status:"validated",createdAt:"2026-10-08T13:00:00Z",payload:{date:DEMO_DATE,service:"midi",ht:156000,vat:18600,ttc:174600,covers:60,reference:"Z-0810-M"}},
  {id:"demo-prior-midi",kind:"cash",title:"Relevé · jeudi précédent, midi",status:"validated",createdAt:"2026-10-01T13:00:00Z",payload:{date:"2026-10-01",service:"midi",ht:187200,vat:22320,ttc:209520,covers:72,reference:"Z-0110-M"}},
  {id:"demo-prior-soir",kind:"cash",title:"Relevé · jeudi précédent, soir",status:"validated",createdAt:"2026-10-01T21:00:00Z",payload:{date:"2026-10-01",service:"soir",ht:124800,vat:14880,ttc:139680,covers:48,reference:"Z-0110-S"}},
  {id:"demo-facture",kind:"invoice",title:"Facture · Marché du Jardin",status:"validated",createdAt:"2026-10-06T09:00:00Z",payload:{date:"2026-10-06",supplier:"Marché du Jardin",reference:"MJ-106",ht:4750,vat:261,ttc:5011,dueDate:"2026-10-20",lines:[{name:"Tomates",quantity:5,unit:"kg",totalHT:1750},{name:"Courgettes",quantity:5,unit:"kg",totalHT:1400},{name:"Huile d’olive",quantity:2,unit:"L",totalHT:1600}]}},
  {id:"demo-note",kind:"note",title:"Le groupe Bernard · ce soir",status:"validated",createdAt:"2026-10-08T09:00:00Z",payload:{date:DEMO_DATE,category:"consigne",text:"Groupe Bernard : 8 personnes à 20 h. Les tables T3 et T4 peuvent être réunies. Vérifier l’affectation avec la salle."}},
];}
export function demoWorkspace():Workspace{return {...emptyWorkspace(),tables:[
  {id:"t1",label:"T1",seats:2,x:14,y:18,shape:"round",zone:"Salle"},{id:"t2",label:"T2",seats:2,x:48,y:18,shape:"round",zone:"Salle"},{id:"t5",label:"T5",seats:6,x:80,y:18,shape:"square",zone:"Salle"},{id:"t3",label:"T3",seats:4,x:14,y:65,shape:"square",zone:"Salle"},{id:"t4",label:"T4",seats:4,x:48,y:65,shape:"square",zone:"Salle"},{id:"t6",label:"T6",seats:6,x:80,y:65,shape:"square",zone:"Salle"}],
  reservations:[{id:"r1",name:"Leclerc",date:DEMO_DATE,time:"20:00",guests:2,tableIds:["t2"],status:"attendue",note:""},{id:"r2",name:"Moreau",date:DEMO_DATE,time:"20:00",guests:5,tableIds:["t5"],status:"installée",note:""},{id:"r3",name:"Bernard",date:DEMO_DATE,time:"20:00",guests:8,tableIds:[],status:"attendue",note:"Tables T3 + T4 réunissables."}],
  ingredients:[{id:"tomate",name:"Tomates",unit:"kg",price:350,sourceId:"demo-facture"},{id:"courgette",name:"Courgettes",unit:"kg",price:280,sourceId:"demo-facture"},{id:"huile",name:"Huile d’olive",unit:"L",price:800,sourceId:"demo-facture"}],
  recipes:[{id:"legumes",name:"Légumes rôtis",portions:10,instructions:"Laver et tailler les légumes. Mélanger avec l’huile. Cuire selon la fiche de la cuisine et vérifier l’assaisonnement avant le service.",items:[{ingredientId:"tomate",quantity:1.5},{ingredientId:"courgette",quantity:1},{ingredientId:"huile",quantity:.15}]}],
  tasks:[{id:"task1",text:"Placer le groupe Bernard",date:DEMO_DATE,assignee:"Emma",done:false},{id:"task2",text:"Préparer les légumes et les sauces",date:DEMO_DATE,assignee:"Karim",done:false}],team:[{id:"emma",name:"Emma",role:"Responsable de salle",notes:""},{id:"karim",name:"Karim",role:"Cuisine",notes:""}]};}
export function demoDraft(kind:"cash"|"invoice"):MemoryItem{return kind==="cash"?{id:"demo-soir",kind,title:"Relevé de caisse · soir",status:"draft",createdAt:"2026-10-08T21:00:00Z",originalName:"releve-soir-exemple.pdf",payload:{date:DEMO_DATE,service:"soir",ht:104000,vat:12400,ttc:116400,covers:40,reference:"Z-0810-S"}}:{id:"demo-new-invoice",kind,title:"Facture · Grossiste Horizon",status:"draft",createdAt:"2026-10-08T10:00:00Z",originalName:"facture-exemple.pdf",payload:{date:DEMO_DATE,supplier:"Grossiste Horizon",reference:"FH-108",ht:4615,vat:254,ttc:4869,dueDate:"2026-10-22",lines:[{name:"Tomates",quantity:5,unit:"kg",totalHT:1900},{name:"Huile d’olive",quantity:2,unit:"L",totalHT:1600},{name:"Semoule",quantity:5,unit:"kg",totalHT:1115}]}};}
