"use client";
import { useState } from "react";
import { Plus,Trash2 } from "lucide-react";
import { cashSchema,invoiceSchema,type Cash,type Invoice,type MemoryItem } from "@/lib/restaurant-memory";
export const moneyInput=(c:number)=>String(c/100);
export const toCents=(v:FormDataEntryValue|null)=>Math.round(Number(String(v??"").replace(",","."))*100);
export function DocumentForm({kind,item,date,busy,onSave}:{kind:"cash"|"invoice";item?:MemoryItem;date:string;busy:boolean;onSave:(input:unknown)=>Promise<void>}){
  const cash=kind==="cash"?cashSchema.safeParse(item?.payload):null;
  const invoice=kind==="invoice"?invoiceSchema.safeParse(item?.payload):null;
  const p:Partial<Cash&Invoice>=(cash?.success?cash.data:invoice?.success?invoice.data:{}) as Partial<Cash&Invoice>;
  const [lines,setLines]=useState<Invoice["lines"]>(invoice?.success?invoice.data.lines:[]);
  async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const common={date:String(f.get("date")),ht:toCents(f.get("ht")),vat:toCents(f.get("vat")),ttc:toCents(f.get("ttc")),reference:String(f.get("reference")||"")};
    await onSave({kind,title:String(f.get("title")),payload:kind==="cash"?{...common,service:f.get("service"),covers:Number(f.get("covers"))}:{...common,supplier:f.get("supplier"),dueDate:f.get("dueDate")||null,lines}});
  }
  return <form onSubmit={submit} className="memory-form"><label>Titre<input name="title" required maxLength={200} defaultValue={item?.title||(kind==="cash"?"Relevé de caisse":"Facture fournisseur")}/></label><div className="memory-form-grid"><label>Date<input type="date" name="date" required defaultValue={p.date||date}/></label><label>Référence<input name="reference" maxLength={200} defaultValue={p.reference}/></label>{kind==="cash"?<><label>Service<select name="service" defaultValue={p.service||"journée"}><option>midi</option><option>soir</option><option>journée</option></select></label><label>Couverts<input type="number" min={0} max={10000} name="covers" required defaultValue={p.covers??0}/></label></>:<><label>Fournisseur<input name="supplier" required maxLength={200} defaultValue={p.supplier}/></label><label>Échéance<input type="date" name="dueDate" defaultValue={p.dueDate||""}/></label></>}</div><div className="memory-form-grid money-fields"><label>HT (€)<input name="ht" type="number" required step="0.01" min={0} defaultValue={moneyInput(p.ht||0)}/></label><label>TVA (€)<input name="vat" type="number" required step="0.01" min={0} defaultValue={moneyInput(p.vat||0)}/></label><label>TTC (€)<input name="ttc" type="number" required step="0.01" min={0} defaultValue={moneyInput(p.ttc||0)}/></label></div>{kind==="invoice"&&<><div className="memory-row"><h3>Produits et conditionnements</h3><button type="button" className="memory-button" onClick={()=>setLines([...lines,{name:"",quantity:1,unit:"kg",totalHT:0}])}><Plus size={14}/>Ajouter une ligne</button></div>{lines.map((line,i)=><div className="memory-invoice-line" key={i}><label>Produit<input value={line.name} required onChange={e=>setLines(lines.map((l,j)=>j===i?{...l,name:e.target.value}:l))}/></label><label>Quantité<input type="number" step="0.001" min="0.001" required value={line.quantity} onChange={e=>setLines(lines.map((l,j)=>j===i?{...l,quantity:Number(e.target.value)}:l))}/></label><label>Unité<select value={line.unit} onChange={e=>setLines(lines.map((l,j)=>j===i?{...l,unit:e.target.value as typeof l.unit}:l))}>{["kg","g","L","ml","pièce"].map(u=><option key={u}>{u}</option>)}</select></label><label>Total HT (€)<input type="number" min={0} step="0.01" required value={line.totalHT/100} onChange={e=>setLines(lines.map((l,j)=>j===i?{...l,totalHT:Math.round(Number(e.target.value)*100)}:l))}/></label><button type="button" className="memory-icon-button" aria-label="Supprimer cette ligne" onClick={()=>setLines(lines.filter((_,j)=>j!==i))}><Trash2 size={16}/></button></div>)}<p className="memory-caption">Les prix de vos ingrédients seront proposés depuis les factures validées. Vérifiez les unités et les conditionnements.</p></>}<button className="memory-button primary" disabled={busy}>{busy?"Enregistrement…":"Valider dans la mémoire · 0 crédit"}</button></form>;
}
