"use client";
import Link from "next/link";
import { useState } from "react";
import { ArrowRight,Check,Database,FileText,LayoutGrid,Receipt,Sparkles } from "lucide-react";
import { RestaurantApp } from "./restaurant-app";
export function MemoryLanding({focus="home"}:{focus?:"home"|"features"|"pricing"}){
  const [added,setAdded]=useState(false);
  return <div className="memory-site"><section className="memory-hero"><div><span className="memory-eyebrow">Votre restaurant. Une mémoire. Un copilote.</span><h1>Toute la vie de votre restaurant.<br/><span>Enfin reliée.</span></h1><p>Déposez vos relevés et vos factures. Retrouvez vos chiffres, votre salle et vos consignes. Votre copilote s’appuie sur cette mémoire pour vous aider à gérer la suite.</p><div className="memory-actions"><Link className="memory-button primary" href="/sign-up">Activer mon copilote <ArrowRight size={16}/></Link><a className="memory-button" href="#demonstration">Explorer la démonstration</a></div><p className="memory-hero-note">29 € / mois · 2 000 crédits IA inclus · Démonstration sans inscription</p></div><div className="memory-hero-scene"><div className="memory-row"><strong>Le Jardin</strong><span className="memory-pill">Exemple fictif</span></div><div className="memory-scene-document"><FileText size={24}/><div className="memory-grow"><strong>{added?"Relevé du soir validé":"Relevé de caisse · midi"}</strong><small>{added?"CA et couverts reliés à la mémoire":"8 octobre · données confirmées"}</small></div><Check size={18}/></div><div className="memory-scene-totals"><div><small>CA TTC</small><strong>{added?"2 910 €":"1 746 €"}</strong></div><div><small>Couverts</small><strong>{added?"100":"60"}</strong></div><div><small>Ticket moyen</small><strong>29,10 €</strong></div></div><button className="memory-button" onClick={()=>setAdded(!added)}><Receipt size={15}/>{added?"Revenir au service de midi":"Ajouter le relevé du soir"}</button><div className="memory-scene-chat"><div className="memory-row"><strong><Sparkles size={16} style={{display:"inline",marginRight:7}}/>Le copilote, avec ses sources</strong></div><p>Le ticket moyen reste stable. Sur les mêmes services, l’écart de chiffre d’affaires correspond à moins de couverts.</p><a href="#demonstration" className="memory-button">Voir les chiffres et les sources <ArrowRight size={15}/></a></div></div></section>
    {focus!=="pricing"&&<section className="memory-section" id="features"><span className="memory-eyebrow">Un restaurant qui n’oublie plus</span><h2>Chaque document enrichit la même mémoire.</h2><div className="memory-story"><ul><li><FileText size={21}/><div><strong>Caisse, CA et couverts</strong><p>Conservez vos relevés, confirmez les montants et comparez les mêmes services. Les calculs restent consultables sans utiliser de crédits IA.</p></div></li><li><Receipt size={21}/><div><strong>Factures et cuisine</strong><p>Gardez l’original et les produits reconnus. Appliquez les prix validés à vos ingrédients, puis adaptez les quantités de vos recettes.</p></div></li><li><LayoutGrid size={21}/><div><strong>Salle, équipe et quotidien</strong><p>Dessinez votre salle, affectez les réservations et transmettez les tâches, les incidents et les décisions de l’équipe.</p></div></li></ul><div className="memory-flow"><div><small>01 · Déposer</small><strong>Une facture, un relevé, une consigne.</strong><p>Photo, PDF ou saisie manuelle : tout rejoint votre espace.</p></div><div><small>02 · Confirmer</small><strong>Vous vérifiez les données reconnues.</strong><p>Un brouillon ne change jamais vos chiffres avant validation.</p></div><div><small>03 · Comprendre</small><strong>Le copilote relie les éléments utiles.</strong><p>Il retrouve ses sources et indique ce qu’il manque pour répondre.</p></div></div></div></section>}
    {focus!=="pricing"&&<section className="memory-demo-section" id="demonstration"><div className="memory-row"><div><span className="memory-eyebrow">Essayez le fonctionnement</span><h2>Un vrai parcours. Des exemples préparés.</h2></div><Link href="/demo" className="memory-button">Ouvrir la démo en grand <ArrowRight size={15}/></Link></div><RestaurantApp demo/></section>}
    <section className="memory-section memory-pricing-section" id="pricing"><div><span className="memory-eyebrow">Un abonnement. Une jauge claire.</span><h2>Votre mémoire reste accessible. Vous maîtrisez l’IA.</h2><p className="memory-section-lead">Le coût d’une analyse est annoncé avant de la lancer. Consulter, corriger, organiser la salle et recalculer les quantités ne consomme aucun crédit. Quand la jauge est vide, ces fonctions restent disponibles.</p><p className="memory-caption" style={{marginTop:20}}>Lecture d’un document : 12 crédits.<br/>Question au copilote : 5 crédits.<br/>Les échecs techniques restituent les crédits.</p></div><div className="memory-price-card"><span className="memory-eyebrow">IA Restaurant · Pro</span><div className="memory-price">29 € <small>/ mois</small></div><p className="memory-caption">Pour gérer votre restaurant avec sa propre mémoire.</p><ul>{["Mémoire, documents originaux et données validées","CA, couverts, factures, recettes et plan de salle","Copilote avec sources et propositions à valider","2 000 crédits IA mensuels · jusqu’à 5 restaurants","Sans engagement · packs de crédits disponibles"].map(v=><li key={v}><Check/>{v}</li>)}</ul><Link className="memory-button primary" href="/sign-up">Créer mon compte et activer le copilote <ArrowRight size={15}/></Link><p className="memory-caption" style={{marginTop:13,textAlign:"center"}}>La création du compte précède le paiement.<br/>Aucune génération IA gratuite sur vos documents.</p></div></section>
    <section className="memory-section memory-faq"><span className="memory-eyebrow">Avant de commencer</span><h2>Quelques réponses utiles.</h2>{[["La démonstration utilise-t-elle vraiment l’IA ?","Non. Elle utilise un restaurant fictif et des réponses préparées. Vous pouvez manipuler les données pour comprendre le parcours sans inscription ni appel IA."],["Mon copilote invente-t-il des chiffres ?","Les indicateurs sont calculés par l’application à partir des données validées. Le copilote consulte votre mémoire et renvoie vers ses sources. Vérifiez ses interprétations ; si les données ne suffisent pas, il doit préciser ce qui manque."],["Faut-il connecter ma caisse ?","Vous pouvez commencer avec des relevés PDF, des photos ou une saisie manuelle. Il n’y a pas de connexion automatique à votre logiciel de caisse dans cette version."],["Que se passe-t-il lorsque mes crédits sont épuisés ?","La lecture IA et les nouvelles analyses s’arrêtent. Votre mémoire, les calculs et les outils de gestion manuelle restent accessibles. Vous pouvez ajouter un pack de crédits depuis votre compte."],["Puis-je calculer mon bénéfice avec les factures ?","Le CA et les achats ne suffisent pas pour un bénéfice complet. Il faut aussi les stocks et consommations, les pertes, les salaires et les autres charges. Le copilote signale les données manquantes."]].map(([q,a])=><details key={q}><summary>{q}</summary><p>{a}</p></details>)}</section><section className="memory-bottom"><Database size={28} style={{margin:"0 auto 18px",color:"var(--memory-green)"}}/><h2>Votre prochain service commence ici.</h2><p>Gardez la mémoire. Préparez la suite.</p><Link className="memory-button primary" href="/sign-up">Activer mon copilote <ArrowRight size={16}/></Link></section>
  </div>;
}
