"use client";
import Link from "next/link";
import { useEffect,useRef,useState } from "react";
import { ArrowRight,BookOpen,ChartNoAxesCombined,Check,ChefHat,Database,Download,FilePlus2,FileText,LayoutGrid,Plus,Receipt,Search,Send,Sparkles,Sun,Users,X } from "lucide-react";
import { cashMetrics,cashOverlaps,cashSchema,daySchema,emptyWorkspace,invoiceSchema,itemInputSchema,latestPrices,parisDay,recipeCost,workspaceSchema,type MemoryItem,type Workspace } from "@/lib/restaurant-memory";
import { DEMO_DATE,demoDraft,demoItems,demoWorkspace } from "@/lib/memory-demo";
import type { CopilotReply } from "@/lib/memory-ai";
import { DocumentForm } from "./document-form";
import { WorkspaceForm,type EditKind } from "./workspace-forms";

const money=(c:number)=>new Intl.NumberFormat("fr-FR",{style:"currency",currency:"EUR"}).format(c/100);
const number=(n:number)=>new Intl.NumberFormat("fr-FR",{maximumFractionDigits:2}).format(n);
const pages=[{id:"today",label:"Aujourd’hui",icon:Sun},{id:"memory",label:"Mémoire",icon:Database},{id:"cash",label:"Caisse & CA",icon:ChartNoAxesCombined},{id:"invoices",label:"Achats & factures",icon:Receipt},{id:"floor",label:"Service & salle",icon:LayoutGrid},{id:"kitchen",label:"Cuisine",icon:ChefHat},{id:"team",label:"Équipe & suivi",icon:Users}] as const;
type Page=typeof pages[number]["id"];
type Restaurant={id:string;name:string};
type Modal={kind:"doc";item?:MemoryItem;docKind:"cash"|"invoice"}|{kind:"source";item:MemoryItem}|{kind:"edit";editKind:EditKind;id?:string}|{kind:"read"}|{kind:"note";text?:string}|{kind:"restaurant"};
type Message={question:string;reply:CopilotReply};
export function RestaurantApp({demo=false,restaurants:initialRestaurants=[],balance:initialBalance=2000,maxCredits=2000,paid=true}:{demo?:boolean;restaurants?:Restaurant[];balance?:number;maxCredits?:number;paid?:boolean}){
  const [restaurants,setRestaurants]=useState(initialRestaurants),[restaurantId,setRestaurantId]=useState(initialRestaurants[0]?.id||"");
  const [workspace,setWorkspace]=useState<Workspace>(demo?demoWorkspace():emptyWorkspace()),[items,setItems]=useState<MemoryItem[]>(demo?demoItems():[]),[revision,setRevision]=useState(0),[balance,setBalance]=useState(demo?740:initialBalance);
  const [page,setPage]=useState<Page>("today"),[date,setDate]=useState(demo?DEMO_DATE:parisDay()),[modal,setModal]=useState<Modal|null>(null),[busy,setBusy]=useState(false),[loading,setLoading]=useState(!demo&&!!restaurantId),[error,setError]=useState(""),[notice,setNotice]=useState(""),[query,setQuery]=useState(""),[question,setQuestion]=useState(""),[messages,setMessages]=useState<Message[]>([]),[portions,setPortions]=useState<Record<string,number>>({});
  const dialogRef=useRef<HTMLDivElement>(null),previousFocus=useRef<HTMLElement|null>(null),hydrated=useRef(false);
  const restaurantName=demo?"Le Jardin":restaurants.find(r=>r.id===restaurantId)?.name||"Mon restaurant";
  const budget=demo?1000:maxCredits;
  const metrics=cashMetrics(items,date),base="/api/memory/"+restaurantId;
  const validated=items.filter(i=>i.status==="validated"),drafts=items.filter(i=>i.status==="draft");
  async function request(url:string,options?:RequestInit){const response=await fetch(url,options);const data=await response.json();if(!response.ok)throw new Error(data.error||"L’opération n’a pas abouti.");return data;}
  const json=(body:unknown,method="POST")=>({method,headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});
  async function operation(fn:()=>Promise<void>){if(busy)return;setBusy(true);setError("");try{await fn();}catch(e){setError(e instanceof Error?e.message:"L’opération n’a pas abouti.");}finally{setBusy(false);}}
  useEffect(()=>{if(!demo||hydrated.current)return;try{const raw=sessionStorage.getItem("ia-restaurant-demo-v3");if(raw){const saved=JSON.parse(raw);const w=workspaceSchema.safeParse(saved.workspace);if(w.success)setWorkspace(w.data);if(Array.isArray(saved.items))setItems(saved.items);if(Number.isInteger(saved.balance))setBalance(Math.max(0,Math.min(1000,saved.balance)));}}catch{}hydrated.current=true;},[demo]);
  useEffect(()=>{if(demo&&hydrated.current)sessionStorage.setItem("ia-restaurant-demo-v3",JSON.stringify({workspace,items,balance}));},[demo,workspace,items,balance]);
  useEffect(()=>{if(demo||!restaurantId)return;let active=true;setLoading(true);setError("");request("/api/memory/"+restaurantId).then(data=>{if(!active)return;setWorkspace(workspaceSchema.parse(data.workspace));setItems(data.items);setRevision(data.revision);setBalance(data.balance);setMessages(data.messages||[]);}).catch(e=>{if(active)setError(e.message);}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;};},[restaurantId,demo]);
  useEffect(()=>{if(!modal)return;previousFocus.current=document.activeElement as HTMLElement;const node=dialogRef.current;node?.querySelector<HTMLElement>("button,input,select,textarea")?.focus();const key=(e:KeyboardEvent)=>{if(e.key==="Escape"&&!busy)setModal(null);if(e.key==="Tab"&&node){const els=Array.from(node.querySelectorAll<HTMLElement>("button:not(:disabled),input,select,textarea,a[href]"));const first=els[0],last=els.at(-1);if(e.shiftKey&&document.activeElement===first){last?.focus();e.preventDefault();}else if(!e.shiftKey&&document.activeElement===last){first?.focus();e.preventDefault();}}};document.addEventListener("keydown",key);return()=>{document.removeEventListener("keydown",key);previousFocus.current?.focus();};},[modal,busy]);
  useEffect(()=>{if(!notice)return;const timer=setTimeout(()=>setNotice(""),5500);return()=>clearTimeout(timer);},[notice]);
  async function saveWorkspace(next:Workspace){workspaceSchema.parse(next);if(!demo){const result=await request(base,json({workspace:next,revision},"PUT"));setRevision(result.revision);}setWorkspace(next);setModal(null);setNotice("Enregistré dans la mémoire · 0 crédit.");}
  async function saveDocument(input:unknown,existing?:MemoryItem){const parsed=itemInputSchema.parse(input);if(demo){
    if(parsed.kind==="cash"&&validated.some(i=>i.id!==existing?.id&&i.kind==="cash"&&cashOverlaps(cashSchema.parse(i.payload),parsed.payload)))throw new Error("Un relevé couvre déjà cette date et ce service.");
    const item:MemoryItem={id:existing?.id||crypto.randomUUID(),...parsed,status:"validated",createdAt:existing?.createdAt||new Date().toISOString(),originalName:existing?.originalName};setItems(previous=>[item,...previous.filter(i=>i.id!==item.id)]);
  }else{const result=await request(base+"/items"+(existing?"/"+existing.id:""),json(parsed,existing?"PATCH":"POST"));setItems(previous=>[result.item,...previous.filter(i=>i.id!==result.item.id)]);}setModal(null);setNotice("Données validées dans la mémoire · 0 crédit.");}
  function simulateReading(kind:"cash"|"invoice"){const item=demoDraft(kind),exists=items.find(i=>i.id===item.id);if(exists){setModal(exists.status==="draft"?{kind:"doc",item:exists,docKind:kind}:{kind:"source",item:exists});return;}if(balance<12){setError("Quota de démonstration atteint. Les données restent accessibles.");return;}setBalance(b=>b-12);setItems(previous=>[item,...previous]);setModal({kind:"doc",item,docKind:kind});setNotice("Exemple préparé · 12 crédits simulés. Vérifiez puis validez les données.");}
  async function readFile(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);f.set("requestId",crypto.randomUUID());await operation(async()=>{const result=await request(base+"/read",{method:"POST",body:f});setBalance(result.balance);setItems(previous=>[result.item,...previous.filter(i=>i.id!==result.item.id)]);setModal({kind:"doc",item:result.item,docKind:result.item.kind});if(result.duplicate)setNotice("Document déjà conservé · aucun crédit consommé.");});}
  async function ask(value:string){if(value.trim().length<3)return;await operation(async()=>{
    if(demo){if(balance<5)throw new Error("Crédits simulés insuffisants. Votre mémoire reste accessible.");const m=cashMetrics(items,date);let reply:CopilotReply;
      if(value.toLowerCase().includes("prix")||value.toLowerCase().includes("facture")){const latest=latestPrices(items).find(p=>p.name==="Tomates");reply={answer:latest?.price===380?"Les tomates passent de 3,50 à 3,80 €/kg, soit +8,6 %. Les conditionnements sont de 5 kg. Vous pouvez appliquer le nouveau prix à votre ingrédient depuis l’espace Achats.":"Les tomates sont au prix confirmé de 3,50 €/kg. Ajoutez puis validez la facture proposée pour comparer le nouveau tarif.",sources:["demo-facture",...(items.some(i=>i.id==="demo-new-invoice"&&i.status==="validated")?["demo-new-invoice"]:[])],missing:[],suggestedNote:null};}
      else if(value.toLowerCase().includes("résultat")||value.toLowerCase().includes("bénéfice"))reply={answer:"Les relevés indiquent "+money(m.ht)+" de CA HT. Les factures sont des achats, elles ne permettent pas à elles seules de calculer le bénéfice. Pour un résultat complet, il faut notamment les consommations et stocks, les salaires, le loyer et les autres charges.",sources:m.sources,missing:["Stocks et consommations","Salaires et autres charges"],suggestedNote:"Compléter les stocks et les charges avant de calculer le résultat."};
      else if(value.toLowerCase().includes("groupe")||value.toLowerCase().includes("table"))reply={answer:"Le groupe Bernard compte 8 personnes. Dans le plan de démonstration, T3 et T4 totalisent 8 places. La consigne enregistrée indique qu’elles peuvent être réunies. Vérifiez les réservations puis affectez le groupe dans Service & salle.",sources:["demo-note"],missing:[],suggestedNote:"Vérifier et confirmer l’affectation du groupe Bernard à T3 et T4."};
      else reply={answer:m.comparison===null?"Les relevés disponibles ne couvrent pas les mêmes services la semaine précédente. Je peux afficher le CA enregistré, mais il manque une période comparable.":"Sur les mêmes services, le CA TTC est de "+money(m.ttc)+" contre "+money(m.previous.ttc)+" le jeudi précédent ("+number(m.comparison)+" %). Les couverts sont "+m.covers+" contre "+m.previous.covers+". Le ticket moyen actuel est "+(m.ticket===null?"non calculable":money(m.ticket))+". Les relevés ne permettent pas à eux seuls de connaître la raison d’un changement de fréquentation.",sources:[...m.sources,...m.referenceSources],missing:[],suggestedNote:null};
      setBalance(b=>b-5);setMessages(previous=>[...previous,{question:value,reply}].slice(-8));
    }else{const result=await request(base+"/copilot",json({question:value,date,requestId:crypto.randomUUID()}));setBalance(result.balance);setMessages(previous=>[...previous,{question:value,reply:result.reply}].slice(-8));}setQuestion("");});}
  function source(id:string){const item=items.find(i=>i.id===id);if(item)setModal({kind:"source",item});else setNotice("La source n’est plus disponible dans cette mémoire.");}
  function exportMemory(){const blob=new Blob([JSON.stringify({restaurant:restaurantName,workspace,items,exportedAt:new Date().toISOString()},null,2)],{type:"application/json"});const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download="memoire-restaurant.json";a.click();URL.revokeObjectURL(url);}
  const button=(label:React.ReactNode,fn:()=>void,primary=false,disabled=false)=><button type="button" className={"memory-button"+(primary?" primary":"")} disabled={busy||disabled} onClick={fn}>{label}</button>;
  const heading=(eyebrow:string,title:string,desc:string)=><div className="memory-page-heading"><span className="memory-eyebrow">{eyebrow}</span><h1>{title}</h1><p>{desc}</p></div>;
  const metric=(label:string,value:React.ReactNode,context:string)=><div className="memory-metric"><span>{label}</span><strong>{value}</strong><small>{context}</small></div>;
  const docs=(list:MemoryItem[])=><div className="memory-documents">{list.length?list.map(i=><button key={i.id} className="memory-document" onClick={()=>setModal(i.status==="draft"&&["cash","invoice"].includes(i.kind)?{kind:"doc",item:i,docKind:i.kind as "cash"|"invoice"}:{kind:"source",item:i})}><span className="memory-document-icon">{i.kind==="invoice"?<Receipt size={19}/>:<FileText size={19}/>}</span><span className="memory-grow"><strong>{i.title}</strong><small>{i.originalName||new Intl.DateTimeFormat("fr-FR",{dateStyle:"medium",timeZone:"Europe/Paris"}).format(new Date(i.createdAt))}</small></span><span className={"memory-pill"+(i.status==="draft"?" pending":"")}>{i.status==="draft"?"À valider":"Conservé"}</span></button>):<p className="memory-empty">Votre mémoire se construit avec vos premiers documents et consignes.</p>}</div>;
  const edit=(editKind:EditKind,id?:string)=>setModal({kind:"edit",editKind,id});
  const last=messages.at(-1);
  return <div className={"restaurant-app"+(demo?" restaurant-demo":"")}>
    <header className="memory-app-header"><Link className="memory-brand" href="/"><span className="memory-logo">ia.</span><span><strong>IA Restaurant</strong><small>La mémoire de votre restaurant</small></span></Link><div className="memory-restaurant-picker">{demo?<strong>Le Jardin</strong>:<><select aria-label="Restaurant actif" value={restaurantId} onChange={e=>setRestaurantId(e.target.value)}><option value="" disabled>Choisir un restaurant</option>{restaurants.map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select><button type="button" className="memory-icon-button" aria-label="Ajouter un restaurant" onClick={()=>setModal({kind:"restaurant"})} disabled={!paid}><Plus size={18}/></button></>}</div>{demo?<Link className="memory-button primary" href="/sign-up">Utiliser avec mon restaurant <ArrowRight size={15}/></Link>:<Link className="memory-button" href="/dashboard/billing">Abonnement</Link>}</header>
    {demo&&<div className="memory-demo-banner"><span><Sparkles size={14}/> Restaurant fictif · exemples préparés · aucun appel IA</span><Link href="/sign-up">Le vrai copilote après paiement</Link></div>}
    <div className="memory-app-shell"><aside className="memory-navigation"><nav aria-label="Gestion du restaurant">{pages.map(p=><button key={p.id} aria-current={page===p.id?"page":undefined} onClick={()=>setPage(p.id)}><p.icon size={18}/>{p.label}</button>)}</nav><div className="memory-budget"><div className="memory-row"><strong>Crédits IA restants</strong><span>{number(balance)}</span></div><div className="memory-progress" role="progressbar" aria-label="Crédits IA restants" aria-valuemin={0} aria-valuemax={Math.max(budget,balance)} aria-valuenow={balance}><span style={{width:Math.min(100,balance/budget*100)+"%"}}/></div><small>{demo?"Jauge simulée · 1 000 crédits":"Dotation mensuelle : "+number(budget)+" crédits"}</small><small>Consultation, calculs et saisie : 0 crédit</small>{!demo&&<Link href="/dashboard/tokens">Ajouter des crédits</Link>}</div></aside>
    <main className="memory-main"><div className="memory-main-toolbar"><span className="memory-caption">{restaurantName}</span><label className="memory-date"><span className="sr-only">Date du service</span><input type="date" value={date} onChange={e=>{if(daySchema.safeParse(e.target.value).success)setDate(e.target.value);}}/></label></div>{error&&<div className="memory-error" role="alert">{error} <button type="button" onClick={()=>setError("")} aria-label="Fermer l’erreur"><X size={16}/></button></div>}{notice&&<div className="memory-notice" role="status">{notice}</div>}{loading?<div className="memory-empty">Ouverture de votre mémoire…</div>:!demo&&!restaurantId?<div className="memory-first"><Database size={35}/><h1>Bienvenue dans votre mémoire.</h1><p>Commencez par ajouter votre restaurant, puis déposez un relevé ou conservez une première consigne.</p>{button("Ajouter mon restaurant",()=>setModal({kind:"restaurant"}),true,!paid)}</div>:<>
    {page==="today"&&<>{heading("Votre service","Votre restaurant, au clair.","Ses documents, ses chiffres et ses décisions, au même endroit.")}<div className="memory-metrics">{metric("CA TTC",metrics.sources.length?money(metrics.ttc):"—",metrics.comparison===null?"Pas de période comparable":number(metrics.comparison)+" % vs J−7, mêmes services")}{metric("Couverts",metrics.sources.length?metrics.covers:"—","Services enregistrés")}{metric("Ticket moyen TTC",metrics.ticket===null?"—":money(metrics.ticket),"CA TTC ÷ couverts")}</div><section className="memory-card memory-highlight"><div className="memory-row"><h2><Sparkles size={18}/>Le point du service</h2><span className="memory-caption">Sources vérifiables</span></div><p>{metrics.sources.length?"Vos relevés sont reliés aux chiffres du service. Le copilote peut les mettre en perspective avec votre mémoire.":"Déposez votre premier relevé de caisse pour retrouver votre CA et vos couverts."}</p>{button("Comprendre mon CA · 5 crédits",()=>ask("Pourquoi mon CA a-t-il changé par rapport au même jour la semaine précédente ?"),true,!demo&&!paid)}</section><section className="memory-card"><div className="memory-row"><h2>Compléter la mémoire</h2><span className="memory-pill pending">{drafts.length} à valider</span></div><div className="memory-actions">{demo?<>{button(<><FilePlus2 size={16}/>Relevé du soir · 12 crédits simulés</>,()=>simulateReading("cash"))}{button(<><Receipt size={16}/>Facture · 12 crédits simulés</>,()=>simulateReading("invoice"))}</>:button(<><FilePlus2 size={16}/>Lire un document · 12 crédits</>,()=>setModal({kind:"read"}),false,!paid)}{button("Saisir une consigne",()=>setModal({kind:"note"}))}</div></section><section className="memory-card"><div className="memory-row"><h2>Documents et consignes</h2><button className="memory-text-button" onClick={()=>setPage("memory")}>Toute la mémoire</button></div>{docs([...drafts,...validated].slice(0,4))}</section></>}
    {page==="memory"&&<>{heading("Une mémoire qui dure","Tout retrouver.","Documents originaux, données confirmées et décisions de votre équipe.")}<label className="memory-search"><Search size={18}/><input placeholder="Chercher un document, un produit, une consigne…" value={query} onChange={e=>setQuery(e.target.value)}/></label><div className="memory-actions">{button("Conserver une note",()=>setModal({kind:"note"}),true)}{button(<><Download size={15}/>Exporter les données</>,exportMemory)}</div><section className="memory-card">{docs(items.filter(i=>(i.title+JSON.stringify(i.payload)).toLocaleLowerCase("fr").includes(query.toLocaleLowerCase("fr"))))}</section></>}
    {page==="cash"&&<>{heading("Des relevés aux chiffres","Caisse & chiffre d’affaires","Les calculs reposent sur les relevés validés, sans consommation IA.")}<div className="memory-metrics">{metric("CA HT",money(metrics.ht),"Relevés du jour")}{metric("TVA des relevés",money(metrics.vat),"Valeurs confirmées")}{metric("CA TTC",money(metrics.ttc),metrics.covers+" couverts")}</div><div className="memory-actions">{button("Saisir un relevé · 0 crédit",()=>setModal({kind:"doc",docKind:"cash"}),true)}{demo?button("Lire le relevé proposé",()=>simulateReading("cash")):button("Lire un PDF ou une photo · 12 crédits",()=>setModal({kind:"read"}),false,!paid)}</div><section className="memory-card"><h2>Relevés de caisse</h2>{docs(items.filter(i=>i.kind==="cash"))}</section><p className="memory-caption">Un relevé de journée ne peut pas être ajouté si un relevé midi ou soir couvre déjà cette date. Les données restent modifiables depuis leur source.</p></>}
    {page==="invoices"&&<>{heading("Fournisseurs et achats","Factures & prix d’achat","Une facture lue reste un brouillon jusqu’à votre validation.")}<div className="memory-actions">{button("Saisir une facture · 0 crédit",()=>setModal({kind:"doc",docKind:"invoice"}),true)}{demo?button("Lire la facture proposée",()=>simulateReading("invoice")):button("Lire une facture · 12 crédits",()=>setModal({kind:"read"}),false,!paid)}</div><section className="memory-card"><h2>Factures conservées</h2>{docs(items.filter(i=>i.kind==="invoice"))}</section><section className="memory-card"><div className="memory-row"><h2>Derniers prix validés</h2>{button("Appliquer aux ingrédients · 0 crédit",()=>operation(async()=>{const prices=latestPrices(items);const ingredients=workspace.ingredients.map(i=>{const p=prices.find(p=>p.name.toLocaleLowerCase("fr")===i.name.toLocaleLowerCase("fr")&&p.unit===i.unit);return p?{...i,price:p.price,sourceId:p.sourceId}:i;});for(const p of prices)if(!ingredients.some(i=>i.name.toLocaleLowerCase("fr")===p.name.toLocaleLowerCase("fr")&&i.unit===p.unit))ingredients.push({id:crypto.randomUUID(),name:p.name,unit:p.unit,price:p.price,sourceId:p.sourceId});await saveWorkspace({...workspace,ingredients});}))}</div><div className="memory-table-wrap"><table><thead><tr><th>Produit</th><th>Prix HT</th><th>Source</th></tr></thead><tbody>{latestPrices(items).map(p=><tr key={p.name+p.unit}><td>{p.name}</td><td>{money(p.price)}/{p.unit}</td><td><button className="memory-text-button" onClick={()=>source(p.sourceId)}>Voir la facture</button></td></tr>)}</tbody></table></div>{!latestPrices(items).length&&<p className="memory-empty">Les produits des factures validées apparaîtront ici.</p>}</section><p className="memory-caption">Les achats ne sont pas le coût de consommation ni le bénéfice. Les marges complètes nécessitent aussi les stocks, pertes et charges.</p></>}
    {page==="floor"&&<>{heading("Plan et réservations","Un service bien placé.","Placez vos tables, affectez les groupes et conservez les consignes.")}<div className="memory-actions">{button(<><Plus size={15}/>Ajouter une table</>,()=>edit("table"))}{button("Nouvelle réservation",()=>edit("reservation"),true)}</div><section className="memory-card"><div className="memory-row"><h2>Plan de salle</h2><span className="memory-caption">{workspace.tables.reduce((n,t)=>n+t.seats,0)} places</span></div><div className="memory-floor" onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();const id=e.dataTransfer.getData("text/plain"),bounds=e.currentTarget.getBoundingClientRect();if(!workspace.tables.some(t=>t.id===id))return;operation(()=>saveWorkspace({...workspace,tables:workspace.tables.map(t=>t.id===id?{...t,x:Math.max(0,Math.min(100,(e.clientX-bounds.left)/bounds.width*100)),y:Math.max(0,Math.min(100,(e.clientY-bounds.top)/bounds.height*100))}:t)}));}}>{workspace.tables.map(t=>{const assigned=workspace.reservations.find(r=>r.date===date&&r.tableIds.includes(t.id)&&!["terminée","annulée"].includes(r.status));return <button draggable={!busy} key={t.id} onDragStart={e=>e.dataTransfer.setData("text/plain",t.id)} onClick={()=>edit("table",t.id)} className={"memory-floor-table "+t.shape+(assigned?" reserved":"")} style={{left:`calc(36px + ${t.x/100} * (100% - 72px))`,top:`calc(35px + ${t.y/100} * (100% - 70px))`}} aria-label={t.label+", "+t.seats+" places, "+(assigned?assigned.name:"libre")}><strong>{t.label}</strong><span>{t.seats} places</span><small>{assigned?assigned.name:"Libre"}</small></button>;})}{!workspace.tables.length&&<p className="memory-empty">Ajoutez vos premières tables pour dessiner la salle.</p>}</div><p className="memory-caption">Déplacez une table ou ouvrez-la pour ajuster sa position et sa capacité. Le plan affiche les affectations du jour ; chaque réservation conserve son heure.</p></section><section className="memory-card"><h2>Réservations · {date}</h2>{workspace.reservations.filter(r=>r.date===date).map(r=><button key={r.id} className="memory-reservation" onClick={()=>edit("reservation",r.id)}><span><strong>{r.time} · {r.name}</strong><small>{r.guests} personnes · {r.tableIds.map(id=>workspace.tables.find(t=>t.id===id)?.label).join(" + ")||"À placer"}</small></span><span className="memory-pill">{r.status}</span></button>)}{!workspace.reservations.some(r=>r.date===date)&&<p className="memory-empty">Aucune réservation enregistrée pour cette date.</p>}</section></>}
    {page==="kitchen"&&<>{heading("Fiches et préparation","Votre cuisine, en mémoire.","Les quantités se recalculent depuis vos recettes et vos prix confirmés.")}<div className="memory-actions">{button("Ajouter une recette",()=>edit("recipe"),true)}{button("Ajouter un ingrédient",()=>edit("ingredient"))}</div>{workspace.recipes.map(recipe=>{const count=portions[recipe.id]||recipe.portions,ratio=count/recipe.portions;return <section className="memory-card" key={recipe.id}><div className="memory-row"><h2><BookOpen size={17}/>{recipe.name}</h2><button className="memory-text-button" onClick={()=>edit("recipe",recipe.id)}>Modifier la fiche</button></div><label className="memory-portions">Portions à préparer<input type="number" min={1} max={1000} value={count} onChange={e=>{const n=Number(e.target.value);if(Number.isInteger(n)&&n>0&&n<=1000)setPortions({...portions,[recipe.id]:n});}}/></label><div className="memory-table-wrap"><table><tbody>{recipe.items.map((it,i)=>{const ingredient=workspace.ingredients.find(v=>v.id===it.ingredientId);return <tr key={i}><td>{ingredient?.name}</td><td>{number(it.quantity*ratio)} {ingredient?.unit}</td><td>{ingredient?.sourceId&&<button className="memory-text-button" onClick={()=>source(ingredient.sourceId!)}>Prix source</button>}</td></tr>;})}</tbody></table></div><p className="memory-recipe-instructions">{recipe.instructions}</p><div className="memory-row"><span className="memory-caption">Coût des ingrédients renseignés · HT</span><strong>{money(Math.round(recipeCost(recipe,workspace)*ratio))}</strong></div></section>;})}{!workspace.recipes.length&&<div className="memory-card memory-empty">Ajoutez des ingrédients, puis une fiche de recette.</div>}<section className="memory-card"><h2>Ingrédients</h2>{workspace.ingredients.map(i=><button key={i.id} className="memory-reservation" onClick={()=>edit("ingredient",i.id)}><strong>{i.name}</strong><span>{money(i.price)}/{i.unit}</span></button>)}</section></>}
    {page==="team"&&<>{heading("Le quotidien du restaurant","Préparer et transmettre.","Tâches, responsables, décisions et consignes restent au même endroit.")}<div className="memory-actions">{button("Ajouter une tâche",()=>edit("task"),true)}{button("Ajouter une personne",()=>edit("team"))}{button("Conserver une consigne",()=>setModal({kind:"note"}))}</div><section className="memory-card"><h2>À faire · {date}</h2>{workspace.tasks.filter(t=>t.date===date).map(t=><label className="memory-task" key={t.id}><input type="checkbox" checked={t.done} disabled={busy} onChange={e=>operation(()=>saveWorkspace({...workspace,tasks:workspace.tasks.map(v=>v.id===t.id?{...v,done:e.target.checked}:v)}))}/><span className={t.done?"done":""}>{t.text}<small>{t.assignee||"Sans responsable"}</small></span><button type="button" className="memory-text-button" onClick={()=>edit("task",t.id)}>Modifier</button></label>)}{!workspace.tasks.some(t=>t.date===date)&&<p className="memory-empty">Aucune tâche pour cette date.</p>}</section><section className="memory-card"><h2>Équipe</h2>{workspace.team.map(p=><button className="memory-reservation" key={p.id} onClick={()=>edit("team",p.id)}><span><strong>{p.name}</strong><small>{p.role}</small></span><span className="memory-caption">{p.notes}</span></button>)}</section><section className="memory-card"><h2>Consignes et décisions</h2>{docs(items.filter(i=>i.kind==="note"))}</section></>}
    </>}</main>
    <aside className="memory-copilot"><h2><span className="memory-orb"><Sparkles size={17}/></span>Votre copilote</h2><p className="memory-caption">{validated.length} éléments confirmés · {restaurantName}</p><p className="memory-copilot-intro">Je m’appuie sur vos documents, vos chiffres et les décisions de votre équipe.</p><span className="memory-eyebrow">{demo?"Questions de démonstration":"Pour commencer"}</span>{["Pourquoi mon CA a-t-il changé ?","Quels prix fournisseurs ont changé ?","Comment placer le groupe Bernard ?","Quel est mon résultat ?"].filter(q=>demo||!q.includes("Bernard")).map(q=><button key={q} className="memory-suggestion" onClick={()=>ask(q)} disabled={busy||(!demo&&!paid)||!restaurantId&&!demo}>{q}<small>Analyse · 5 crédits{demo?" simulés":""}</small></button>)}{last&&<div className="memory-answer" aria-live="polite"><span className="memory-caption">{last.question}</span><p>{last.reply.answer}</p>{last.reply.missing.length>0&&<div className="memory-missing"><strong>À compléter</strong><ul>{last.reply.missing.map(m=><li key={m}>{m}</li>)}</ul></div>}<div className="memory-sources">{last.reply.sources.map(id=><button key={id} onClick={()=>source(id)}><FileText size={12}/>{items.find(i=>i.id===id)?.title||"Source conservée"}</button>)}</div>{last.reply.suggestedNote&&button("Conserver cette proposition",()=>setModal({kind:"note",text:last.reply.suggestedNote!}))}</div>}{!demo&&<form className="memory-composer" onSubmit={e=>{e.preventDefault();ask(question);}}><label className="sr-only" htmlFor="memory-question">Question au copilote</label><textarea id="memory-question" value={question} onChange={e=>setQuestion(e.target.value)} placeholder="Posez une question sur votre restaurant…" maxLength={2000} rows={3}/><button className="memory-button primary" disabled={busy||!paid||!restaurantId||question.trim().length<3}><Send size={15}/>{busy?"Analyse…":"Envoyer · 5 crédits"}</button></form>}<p className="memory-caption">{demo?"Réponses préparées pour cet exemple. Les chiffres et les documents sont fictifs.":"Les documents restent vos sources. Vérifiez une proposition avant de la conserver ou de l’appliquer."}</p></aside></div>
    {modal&&<div className="memory-dialog-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget&&!busy)setModal(null);}}><div className="memory-dialog" ref={dialogRef} role="dialog" aria-modal="true" aria-labelledby="memory-dialog-title"><div className="memory-row"><span className="memory-eyebrow">{demo?"Démonstration":"Votre restaurant"}</span><button type="button" className="memory-icon-button" onClick={()=>setModal(null)} disabled={busy} aria-label="Fermer"><X size={20}/></button></div><h2 id="memory-dialog-title">{modal.kind==="doc"?(modal.docKind==="cash"?"Vérifier le relevé de caisse":"Vérifier la facture"):modal.kind==="source"?modal.item.title:modal.kind==="read"?"Lire un document":modal.kind==="note"?"Conserver dans la mémoire":modal.kind==="restaurant"?"Ajouter votre restaurant":({table:"Une table",reservation:"Une réservation",ingredient:"Un ingrédient",recipe:"Une fiche de recette",task:"Une tâche",team:"Une personne"}[modal.editKind])}</h2>{error&&<div className="memory-error" role="alert">{error}</div>}
    {modal.kind==="doc"&&<DocumentForm key={modal.item?.id||modal.docKind} kind={modal.docKind} item={modal.item} date={date} busy={busy} onSave={input=>operation(()=>saveDocument(input,modal.item))}/>}
    {modal.kind==="edit"&&<WorkspaceForm key={modal.editKind+(modal.id||"")} kind={modal.editKind} id={modal.id} data={workspace} date={date} busy={busy} onSave={next=>operation(()=>saveWorkspace(next))}/>}
    {modal.kind==="read"&&<form className="memory-form" onSubmit={readFile}><p>La lecture utilise 12 crédits. Vérifiez les données proposées avant de les ajouter à vos chiffres. Un échec technique restitue les crédits.</p><label>Type<select name="kind"><option value="cash">Relevé de caisse</option><option value="invoice">Facture fournisseur</option></select></label><label>Document original<input type="file" name="file" accept="application/pdf,image/jpeg,image/png,image/webp" required/></label><p className="memory-caption">PDF, JPG, PNG ou WebP · 4 Mo maximum · original conservé dans votre mémoire.</p><button className="memory-button primary" disabled={busy||balance<12}>{busy?"Lecture du document…":"Lire le document · 12 crédits"}</button></form>}
    {modal.kind==="note"&&<form className="memory-form" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);operation(()=>saveDocument({kind:"note",title:String(f.get("title")),payload:{text:String(f.get("text")),category:String(f.get("category")),date}}));}}><label>Titre<input name="title" required maxLength={200} defaultValue="Consigne du service"/></label><label>Catégorie<select name="category">{["consigne","décision","incident","équipe","autre"].map(v=><option key={v}>{v}</option>)}</select></label><label>À retenir<textarea name="text" rows={6} required maxLength={10000} defaultValue={modal.text}/></label><button className="memory-button primary" disabled={busy}>Conserver · 0 crédit</button></form>}
    {modal.kind==="restaurant"&&<form className="memory-form" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);operation(async()=>{const result=await request("/api/restaurants",json({name:String(f.get("name")),cuisine:String(f.get("cuisine")),city:String(f.get("city"))}));setRestaurants([...restaurants,result.restaurant]);setRestaurantId(result.restaurant.id);setModal(null);});}}><label>Nom du restaurant<input name="name" required maxLength={200}/></label><label>Cuisine<input name="cuisine" maxLength={200}/></label><label>Ville<input name="city" maxLength={200}/></label><button className="memory-button primary" disabled={busy||!paid}>Créer mon espace</button></form>}
    {modal.kind==="source"&&<><span className="memory-pill">Source {modal.item.status==="validated"?"confirmée":"à valider"}</span>{modal.item.kind==="note"?<p className="memory-source-text">{String((modal.item.payload as {text:string}).text)}</p>:<><div className="memory-source-details">{Object.entries(modal.item.payload as Record<string,unknown>).filter(([key])=>key!=="lines").map(([key,value])=><div key={key}><span>{({date:"Date",service:"Service",ht:"HT",vat:"TVA",ttc:"TTC",covers:"Couverts",supplier:"Fournisseur",reference:"Référence",dueDate:"Échéance"} as Record<string,string>)[key]||key}</span><strong>{["ht","vat","ttc"].includes(key)?money(Number(value)):String(value??"—")}</strong></div>)}</div>{modal.item.kind==="invoice"&&<div className="memory-table-wrap"><table><tbody>{invoiceSchema.parse(modal.item.payload).lines.map((l,i)=><tr key={i}><td>{l.name}</td><td>{number(l.quantity)} {l.unit}</td><td>{money(l.totalHT)} HT</td></tr>)}</tbody></table></div>}</>}{modal.item.history&&modal.item.history.length>0&&<details className="memory-history"><summary>{modal.item.history.length} version(s) conservée(s) avant correction</summary>{modal.item.history.map((v,i)=><div key={i}><strong>{v.title}</strong><small> · {new Date(v.at).toLocaleString("fr-FR")}</small><p>{v.status==="draft"?"Proposition avant validation":"Données confirmées avant correction"}{typeof (v.payload as {ttc?:number}).ttc==="number"?" · "+money((v.payload as {ttc:number}).ttc)+" TTC":""}</p></div>)}</details>}<div className="memory-actions">{modal.item.hasFile&&!demo&&<a className="memory-button" href={base+"/items/"+modal.item.id+"/file"} target="_blank" rel="noreferrer">Document original</a>}{["cash","invoice"].includes(modal.item.kind)&&button("Corriger les données · 0 crédit",()=>setModal({kind:"doc",item:modal.item,docKind:modal.item.kind as "cash"|"invoice"}))}{button("Supprimer de la mémoire",()=>{if(!confirm("Supprimer ce document et ses données de votre mémoire ?"))return;operation(async()=>{if(!demo){await request(base+"/items/"+modal.item.id,{method:"DELETE"});const current=await request(base);setWorkspace(current.workspace);setRevision(current.revision);}setItems(items.filter(i=>i.id!==modal.item.id));setModal(null);setNotice("Document supprimé.");});})}</div></>}
    </div></div>}
  </div>;
}
