"use client";
import { useState } from "react";
import type { Workspace } from "@/lib/restaurant-memory";
import { toCents } from "./document-form";
export type EditKind="table"|"reservation"|"ingredient"|"recipe"|"task"|"team";
export function WorkspaceForm({kind,data,date,id,busy,onSave}:{kind:EditKind;data:Workspace;date:string;id?:string;busy:boolean;onSave:(data:Workspace)=>Promise<void>}){
  const collection={table:"tables",reservation:"reservations",ingredient:"ingredients",recipe:"recipes",task:"tasks",team:"team"} as const;
  const key=collection[kind];const old=data[key].find(v=>v.id===id);
  const record=(old||{}) as Record<string,unknown>;
  const [selected,setSelected]=useState<string[]>((record.tableIds||[]) as string[]);
  const [ingredients,setIngredients]=useState<Array<{ingredientId:string;quantity:number}>>((record.items||[]) as Array<{ingredientId:string;quantity:number}>);
  const field=(name:string,fallback="")=>String(record[name]??fallback);
  async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget),value=(n:string)=>String(f.get(n)||"");const base={id:id||crypto.randomUUID()};let item:unknown;
    if(kind==="table")item={...base,label:value("label"),seats:Number(f.get("seats")),x:Number(f.get("x")),y:Number(f.get("y")),shape:value("shape"),zone:value("zone")};
    if(kind==="reservation")item={...base,name:value("name"),date:value("date"),time:value("time"),guests:Number(f.get("guests")),tableIds:selected,status:value("status"),note:value("note")};
    if(kind==="ingredient")item={...base,name:value("name"),unit:value("unit"),price:toCents(f.get("price")),sourceId:value("name")===record.name && value("unit")===record.unit && toCents(f.get("price"))===record.price ? record.sourceId||null : null};
    if(kind==="recipe")item={...base,name:value("name"),portions:Number(f.get("portions")),instructions:value("instructions"),items:ingredients};
    if(kind==="task")item={...base,text:value("text"),date:value("date"),assignee:value("assignee"),done:record.done||false};
    if(kind==="team")item={...base,name:value("name"),role:value("role"),notes:value("notes")};
    const next={...data,[key]:id?data[key].map(v=>v.id===id?item:v):[...data[key],item]};await onSave(next as Workspace);
  }
  return <form className="memory-form" onSubmit={submit}>
    {kind==="table"&&<><label>Nom de la table<input name="label" required defaultValue={field("label","T"+(data.tables.length+1))}/></label><div className="memory-form-grid"><label>Places<input name="seats" required type="number" min={1} max={50} defaultValue={field("seats","4")}/></label><label>Zone<input name="zone" required defaultValue={field("zone","Salle")}/></label><label>Forme<select name="shape" defaultValue={field("shape","square")}><option value="square">Rectangle</option><option value="round">Ronde</option></select></label><label>Position horizontale (%)<input name="x" type="number" min={0} max={100} defaultValue={field("x","25")}/></label><label>Position verticale (%)<input name="y" type="number" min={0} max={100} defaultValue={field("y","25")}/></label></div></>}
    {kind==="reservation"&&<><label>Nom<input name="name" required defaultValue={field("name")}/></label><div className="memory-form-grid"><label>Date<input name="date" type="date" required defaultValue={field("date",date)}/></label><label>Heure<input name="time" type="time" required defaultValue={field("time","20:00")}/></label><label>Personnes<input name="guests" required type="number" min={1} max={500} defaultValue={field("guests","2")}/></label><label>État<select name="status" defaultValue={field("status","attendue")}>{["attendue","installée","terminée","annulée"].map(s=><option key={s}>{s}</option>)}</select></label></div><fieldset><legend>Tables affectées</legend><div className="memory-checkboxes">{data.tables.map(t=><label key={t.id}><input type="checkbox" checked={selected.includes(t.id)} onChange={e=>setSelected(e.target.checked?[...selected,t.id]:selected.filter(id=>id!==t.id))}/>{t.label} · {t.seats} places</label>)}</div></fieldset><label>Consigne<textarea name="note" defaultValue={field("note")}/></label><p className="memory-caption">Les affectations réservent deux heures. Les capacités et les chevauchements sont vérifiés avant l’enregistrement.</p></>}
    {kind==="ingredient"&&<><label>Ingrédient<input name="name" required defaultValue={field("name")}/></label><div className="memory-form-grid"><label>Unité de base<select name="unit" defaultValue={field("unit","kg")}>{["kg","L","pièce"].map(u=><option key={u}>{u}</option>)}</select></label><label>Prix HT par unité (€)<input name="price" type="number" required step="0.01" min={0} defaultValue={Number(record.price||0)/100}/></label></div></>}
    {kind==="recipe"&&<><label>Nom de la recette<input name="name" required defaultValue={field("name")}/></label><label>Portions de la fiche<input name="portions" type="number" min={1} max={1000} required defaultValue={field("portions","10")}/></label><div className="memory-row"><h3>Ingrédients</h3><button type="button" className="memory-button" disabled={!data.ingredients.length} onClick={()=>setIngredients([...ingredients,{ingredientId:data.ingredients[0].id,quantity:1}])}>Ajouter</button></div>{ingredients.map((it,i)=><div className="memory-form-grid" key={i}><label>Ingrédient<select value={it.ingredientId} onChange={e=>setIngredients(ingredients.map((v,j)=>j===i?{...v,ingredientId:e.target.value}:v))}>{data.ingredients.map(v=><option key={v.id} value={v.id}>{v.name} ({v.unit})</option>)}</select></label><label>Quantité de la fiche<input type="number" min="0.001" step="0.001" required value={it.quantity} onChange={e=>setIngredients(ingredients.map((v,j)=>j===i?{...v,quantity:Number(e.target.value)}:v))}/></label><button type="button" className="memory-text-button" onClick={()=>setIngredients(ingredients.filter((_,j)=>j!==i))}>Retirer</button></div>)}<label>Préparation<textarea name="instructions" rows={5} defaultValue={field("instructions")}/></label></>}
    {kind==="task"&&<><label>À faire<input name="text" required maxLength={200} defaultValue={field("text")}/></label><div className="memory-form-grid"><label>Date<input type="date" name="date" required defaultValue={field("date",date)}/></label><label>Responsable<input name="assignee" defaultValue={field("assignee")}/></label></div></>}
    {kind==="team"&&<><label>Nom<input name="name" required defaultValue={field("name")}/></label><label>Rôle<input name="role" defaultValue={field("role")}/></label><label>Consignes<textarea name="notes" defaultValue={field("notes")}/></label></>}
    <button className="memory-button primary" disabled={busy}>{busy?"Enregistrement…":"Enregistrer · 0 crédit"}</button>
  </form>;
}
